DROP TABLE JOB IF EXISTS;

CREATE TABLE JOB (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name          VARCHAR(255),
  developer_firstname   VARCHAR(255),
  developer_lastname    VARCHAR(255),
  start_date            DATE,
  description           VARCHAR(255)
);
