INSERT INTO SKILL (ID, NAME) VALUES (default, 'Java');
INSERT INTO SKILL (ID, NAME) VALUES (default, 'Angular');
INSERT INTO SKILL (ID, NAME) VALUES (default, 'Kotlin');
INSERT INTO SKILL (ID, NAME) VALUES (default, 'OpenShift');
INSERT INTO SKILL (ID, NAME) VALUES (default, 'Google Cloud');
INSERT INTO SKILL (ID, NAME) VALUES (default, 'AWS');

INSERT INTO COMPANY (ID, NAME, ADDRESS, CITY, TELEPHONE) VALUES (default, 'Craftsmen', 'Herenweg 82', 'Wilnis', '0302270934');
INSERT INTO COMPANY (ID, NAME, ADDRESS, CITY, TELEPHONE) VALUES (default, 'TechForce1', 'De Regenboog 51', 'Nieuwkoop', '0302271818');
INSERT INTO COMPANY (ID, NAME, ADDRESS, CITY, TELEPHONE) VALUES (default, 'CodeFoundry', 'Smaragd 6', 'McFarland', '0302270099');

INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Dazzling', 'Developer', 1);
INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Exciting', 'Engineer', 1);
INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Funny', 'Frontender', 1);
INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Optimistic', 'Opser', 2);
INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Amazing', 'Angularian', 3);
INSERT INTO DEVELOPER (ID, FIRSTNAME, LASTNAME, COMPANY_ID) VALUES (default, 'Confident', 'Cloud engineer', 1);

INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (1, 3);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (2, 1);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (2, 3);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (2, 4);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (3, 2);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (4, 4);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (4, 5);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (4, 6);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (5, 2);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (6, 1);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (6, 3);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (6, 5);
INSERT INTO DEVELOPER_SKILLS (DEVELOPER_ID, SKILL_ID) VALUES (6, 6);