POST http://localhost:8080/job/new
Content-Type: application/json

{
  "startDate" : "2023-11-01",
  "description": "Kotlin developer bij de NS",
  "project" : {
    "name": "Developer NS"
  },
  "developer" : {
    "firstName": "Exciting",
    "lastName": "Engineer"
  }
}
