INSERT INTO PROJECT VALUES (default, 'Developer Kadaster');
INSERT INTO PROJECT VALUES (default, 'Developer Belastingdienst');
INSERT INTO PROJECT VALUES (default, 'Developer BOL');
INSERT INTO PROJECT VALUES (default, 'Developer NS');

INSERT INTO SKILL VALUES (default, 'Java');
INSERT INTO SKILL VALUES (default, 'Angular');
INSERT INTO SKILL VALUES (default, 'Kotlin');
INSERT INTO SKILL VALUES (default, 'OpenShift');
INSERT INTO SKILL VALUES (default, 'Google Cloud');
INSERT INTO SKILL VALUES (default, 'AWS');

INSERT INTO PROJECT_SKILLS VALUES (1, 3);
INSERT INTO PROJECT_SKILLS VALUES (1, 4);
INSERT INTO PROJECT_SKILLS VALUES (2, 1);
INSERT INTO PROJECT_SKILLS VALUES (2, 2);
INSERT INTO PROJECT_SKILLS VALUES (2, 4);
INSERT INTO PROJECT_SKILLS VALUES (3, 1);
INSERT INTO PROJECT_SKILLS VALUES (3, 2);
INSERT INTO PROJECT_SKILLS VALUES (4, 3);
